name = "laps"
type = "javascript"
account_id = "8cb711746bd0906ad5c15a19f1d2dd88"
workers_dev = true
route = ""
zone_id = ""
kv_namespaces = [ 
 { binding = "PSI", id = "9439a095e8ef4740aa7d3d8e663452af" }
]

[triggers]
crons = ["*/5 * * * *"]
